export const API_URL = 'http://localhost:3000'
export const CLIENT_URL = ''
export const API_TOKEN = 'qXLIZrYCWktaQfHW2VTiHUcvffhR8HfU4LKfFOkF'
export const API_NETWORK_GUID = 'a24fe645-b80d-44dd-9dac-40c6d86eb879'
export const API_NETWORK_OLD_GUID = '3ba0e285-a314-4062-ac9e-aeabeb714e77'
export const GET_MENU_ENDPOINT = '/nilp/api/menu/get'
export const GET_SPECIFIC_PAGE_ENDPOINT = process.env.NODE_ENV != 'production' ? 'https://ullas.education.gov.in/nilpapi/api/v1/cms/page/detail' : 'https://ullas.education.gov.in/nilpapi/api/v1/cms/page/detail'
export const GET_SPECIFIC_POST_ENDPOINT = '/nilp/api/post/get'
export const GET_POST_ENDPOINT = '/nilp/api/post/get-all'
export const GET_CONTENT_BLOCK_ENDPOINT = '/nilp/api/content-block/get'
export const BASE_URL = 'https://nilp.education.gov.in/nadmin/web/'
export const FETCH_LEARNERS = 'fetch_learners'

export const GET_REGION_ENDPOINT = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/get_region_information' : '/nilpapi/api/v1/user/get_region_information'
export const GET_STATES = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/items/master_state' : '/nilpapi/api/v1/items/master_state'
export const GET_DISTRICT = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/items/master_district' : '/nilpapi/api/v1/items/master_district'
export const POST_REGISTER_ENDPOINT = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/member/register' : '/nilpapi/api/v1/user/member/register'
export const POST_VT_REGISTER_ENDPOINT = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/web/fetch_learners' : '/nilpapi/api/v1/user/web/fetch_learners'
export const EXISTS_ENDPOINT = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/member/exists' : '/nilpapi/api/v1/user/member/exists'
export const POST_GENERATE_OTP = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/vt/generate_otp' : '/nilpapi/api/v1/user/vt/generate_otp'
export const POST_VALIDATE_OTP = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/auth/validate-otp' : '/nilpapi/api/v1/user/auth/validate-otp'
export const POST_TAGGING_LEARNERS = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/user/web/vt/tagging' : '/nilpapi/api/v1/user/web/vt/tagging'
export const TOTAL_VISITORS = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/web/visitor-count' : '/nilpapi/api/v1/web/visitor-count'
export const TOTAL_LEARNERS = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/web/literacy_counter' : '/nilpapi/api/v1/web/literacy_counter'
export const MAP_STATS = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/web/map-stats' : '/nilpapi/api/v1/web/map-stats'

export const EXAM_LIST = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/nios/exam-list' : '/nilpapi/api/v1/nios/exam-list'
export const GENERATE_OTP = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/nios/learner/generate-otp' : '/nilpapi/api/v1/nios/learner/generate-otp'
export const VALIDATE_OTP = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/nios/learner/validate-otp' : '/nilpapi/api/v1/nios/learner/validate-otp'
export const MARKS_LIST = process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/nios/learner/list' : '/nilpapi/api/v1/nios/learner/list'
export const DOWNLOAD_CERTIFICATE =process.env.NODE_ENV != 'production' ? '/external-api/nilpapi/api/v1/nios/download-result' : '/nilpapi/api/v1/nios/download-result'