export const CONSTANTS = {
  REQUEST_FORMAT: 'application/json',
  RESPONSE_FORMAT: 'application/json',
  MULTI_FORM: 'multipart/form-data',
  REQUEST_POST: 'POST',
  REQUEST_GET: 'GET',
  LANGUAGE_ENGLISH: 'en',
  SECRET_KEY: "37ZA3D89B64C115122DF9178C8R99c1x",
  IV: "213A26DBB4A358C5",
  SIGNATURE_KEY: "QD32VdbRuMa0iI0q9q7cH6FIHGcNWGdEZOLyK669",
  CIPHER_KEY: "aes-256-cbc",
  HASHING_ALGORITHM: "sha256",
  WEBSITE_NAME: "NILP",
  HEADER_MENU_SLUG: "header-menu",
  FOOTER_QUICK_MENU_SLUG: "quick-links-menu",
  FOOTER_OTHER_MENU_SLUG: "other-links-menu",
  FOOTER_BOTTOM_MENU_SLUG: "footer-bottom-menu",
  CONCISE_PRIMER_URL:'concise-primer',
  MARK_AS_VT:'8ecf3868-03b7-4ea1-8520-e619d793ed7d',
  MARK_AS_LEARNER:'8ca80f73-afd2-4d3f-b41d-e5bea0254b98',
  STATUS_SUCCESS: 'success',
  STATUS_FAILED: 'failed',
  X_AUTHORIZATION_TOKEN: 'MOW1fHHRwyEi-RRRB88FYtxZw_6Swex6',
  SUCCESS:'success'
};
